<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/ElementTanlash_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

In [3]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df=pd.DataFrame(data)

In [4]:
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
series=df['calories']
series

0    420
1    380
2    390
Name: calories, dtype: int64

In [7]:
type(series)

pandas.core.series.Series

In [10]:
v=series[1]
v

380

In [11]:
type(v)

numpy.int64

In [12]:
series[[1]]

1    380
Name: calories, dtype: int64

In [13]:
type(series[[2]])

pandas.core.series.Series

In [15]:
obj=pd.Series(np.arange(8.),index=['a','b','c','d','e','f','h','g'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
h    6.0
g    7.0
dtype: float64

In [17]:
obj['a']

0.0

In [18]:
obj[obj>5]

h    6.0
g    7.0
dtype: float64

In [21]:
obj1=pd.Series(np.arange(8.),index=['10','11','13','14','15','16','17','18'])
obj1

10    0.0
11    1.0
13    2.0
14    3.0
15    4.0
16    5.0
17    6.0
18    7.0
dtype: float64

In [24]:
obj1['18']

7.0